#!/system/bin/sh
ui_print ""
ui_print "╭━━━┳╮╭╮╭┳╮╱╱╭┳━━━┳━━━╮╭┳┳╮"
ui_print "╰╮╭╮┃┃┃┃┃┃╰╮╭╯┃╭━╮┃╭━╮┃┃┃┃┃"
ui_print "╱┃┃┃┃┃┃┃┃┣╮╰╯╭┫┃╱┃┃╰━╯┃┃┃┃┃"
ui_print "╱┃┃┃┃╰╯╰╯┃╰╮╭╯┃┃╱┃┃╭╮╭╯╰┻┻╯"
ui_print "╭╯╰╯┣╮╭╮╭╯╱┃┃╱┃╰━╯┃┃┃╰╮╭┳┳╮"
ui_print "╰━━━╯╰╯╰╯╱╱╰╯╱╰━━━┻╯╰━╯╰┻┻╯"
ui_print ""
ui_print "[====================================================]"
ui_print "|         >>> BACKGROUND APP SLAYER MODULE <<<       |"
ui_print "[====================================================]"
ui_print "| - Automatically closes background applications     |"
ui_print "| - Works based on 3 configurable modes:             |"
ui_print "|     1 = Normal     2 = Aggressive     3 = Extreme  |"
ui_print "| - Uses whitelist, gamelist, and extreme list files |"
ui_print "| - Helps reclaim RAM and improve system efficiency  |"
ui_print "[----------------------------------------------------]"
ui_print "|           Thanks to: My Self and ChatGPT           |"
ui_print "[====================================================]"
ui_print ""
